### ISSUE TITLE
Updated flappy planes

### ISSUE THREAD

**Issue by okidoki4830** [ShashankDont/5-Guy-Games#16]
I added control selection functionality allowing players to choose between:
   - Keyboard control (Space bar)
   - Mouse control (Mouse click)

1. flappy_planes.html:
   - Added control selection buttons
   - Added proper CSS file linking
   - Added control instruction display

2. flappy_styles.css:
   - Added styling for control selection menu
   - Added styles for button states (selected/unselected)
   - Added styling for control instructions

3. game.js:
   - Implemented control selection logic
   - Added mouse click event handling
   - Added keyboard event handling
   - Fixed game speed consistency across different devices
   - Added control type persistence

**Comment by ShashankDont** [comment]
Good job there is still some errors to be fixed
